# System routes
healthcheck:
  path: /carbon-net-zero/healthcheck_r53
  controller: App\Controller\LandingPageController::healthcheck

# GM PAGES
landing_page:
  path: /carbon-net-zero/landing-page
  controller: App\Controller\LandingPageController::landingPage 

question_page:
  path: /carbon-net-zero/journey/{journeyId}/{journeyInstanceId}/{questionUuid}/{gPage}
  controller: App\Controller\GuideMatchJourneyController::journey
  defaults:
    gPage: 0

result_page:
  path: /carbon-net-zero/result-page
  controller: App\Controller\ResultPageController::resultPage


# Tactical back to search
back_to_search:
  path: /carbon-net-zero/back-to-search-results/
  controller: App\Controller\TacticalSerchResultController:backToSearch

start-journey:
  path: /carbon-net-zero/start-journey/{journeyUuidAndDomain}
  controller: App\Controller\StartJourneyController:startJourney

back-to-previous:
  path: /carbon-net-zero/journey-back/{journeyId}/{journeyInstanceId}/{questionUuid}/{journeyHistory}/{gPage}
  controller: App\Controller\GuideMatchBackToPreviousController::backToPrevious
  defaults:
    gPage: 0

journey-result:
  path: /carbon-net-zero/result/{journeyId}/{journeyInstanceId}/{agreements?}
  controller: App\Controller\GuideMatchJourneyResultController::journeyResult


contact-ccs-page:
  path: /carbon-net-zero/contact-ccs/{journeyId}/{journeyInstanceId}/{questionUuid}/{journeyHistory}/{gPage}
  controller: App\Controller\GuideMatchContactCssController::contactCss

contact-ccs-page-journeys:
  path: /carbon-net-zero/contact-ccs-journeys/
  controller: App\Controller\GuideMatchContactCssJourneysController::contactCss

guided-match-journeys:
  path: /carbon-net-zero/guidedmatch
  controller: App\Controller\GuidedMatchJourneysController:searchJourneys

guided-match-health-check:
  path: /guided-match/health-check
  controller: App\Controller\GuidedMatchHealthCheckController:testHealth
  
# carbon net zero 
CNZ_landing_page:
  path: /carbon-net-zero/find-a-carbon-net-zero-solution
  controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
  defaults:
    template: /pages/CNZ_landing_page.html.twig